name: Test

on: push

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout code
        
      - name: Install dependencies
        run: npm install